### PR TITLE
Bug 2041087: sync with u/s metallb-operator

### PR DESCRIPTION
**Pull request by liornoy**
syncing commits merged to upstream metallb-operator repo between 7.1 to 25.1

### CODE REVIEW

**Comment by fedepaol** [comment]
/retitle Bug 2044819: sync with u/s metallb-operator

**Comment by liornoy** [comment]
> SPEAKER_SELECTOR

sure, will do

**Comment by fedepaol** [comment]
/retitle Bug 2041087: sync with u/s metallb-operator

**Review by asood-rh — APPROVED** [review]
/label qe-approved

**Comment by fedepaol** [comment]
/override ci/prow/metallb-e2e-metal-ipi 
/override ci/prow/metallb-e2e-metal-ipi-ovn

Chicken and egg issue, because we changed the label here but metallb tests are still using the old ones.

**Pull request merged**
