### PR TITLE
Bug 2042181: AddressPool validation webhook: Add BGPAdvertisements validation

### PR DESCRIPTION
**Pull request by sabinaaledort**

### CODE REVIEW

**Comment by msherif1234** [comment]
this identical to #58 which is already merged ?

**Comment by sabinaaledort** [comment]
> this identical to #58 which is already merged ?

this one is the fix for the 4.10 branch, while #58 is for main which is now 4.11

**Comment by sabinaaledort** [comment]
the cherry-pick to 4.10 is done by the CI bot in https://github.com/openshift/metallb-operator/pull/60

**Pull request closed without merging**
