### PR TITLE
Add vendor packages and rebase with upstream

### PR DESCRIPTION
**Pull request by msherif1234**

### CODE REVIEW

**Comment by fedepaol** [comment]
A couple of comments about adding the vendor folder:
- we need to copy the vendor folder in the dockerfile
- we need to run the build with -mod=vendor, otherwise vendor won't be used

Then, I am a bit torn about having vendor only d/s, but I think the build will fail if vendor is not aligned with go.mod . The problem will arise when u/s introduces a new dependency and go.mod will drift from what's vendored
The alternative is vendoring u/s and consuming it d/s. 
Thoughts?

**Comment by msherif1234** [comment]
> A couple of comments about adding the vendor folder:
> 
> * we need to copy the vendor folder in the dockerfile
> * we need to run the build with -mod=vendor, otherwise vendor won't be used
> 
> Then, I am a bit torn about having vendor only d/s, but I think the build will fail if vendor is not aligned with go.mod . The problem will arise when u/s introduces a new dependency and go.mod will drift from what's vendored
> The alternative is vendoring u/s and consuming it d/s.
> Thoughts?

That will be ideal if we have the vendoring done upstream so we will gurnatee both stays in sync in that case we can do the above in upstream dockerfile as well and just mirror it downsteam

**Comment by fedepaol** [comment]
> > A couple of comments about adding the vendor folder:
> > 
> > * we need to copy the vendor folder in the dockerfile
> > * we need to run the build with -mod=vendor, otherwise vendor won't be used
> > 
> > Then, I am a bit torn about having vendor only d/s, but I think the build will fail if vendor is not aligned with go.mod . The problem will arise when u/s introduces a new dependency and go.mod will drift from what's vendored
> > The alternative is vendoring u/s and consuming it d/s.
> > Thoughts?
> 
> That will be ideal if we have the vendoring done upstream so we will gurnatee both stays in sync in that case we can do the above in upstream dockerfile as well and just mirror it downsteam

Yes, on the other hand vendoring is considered "legacy practice" which I believe is the reason why for example u/s metallb itself doesn't have the vendor folder in (and that's why I said I am torn :-) ).
Let's keep it this way, go complains if go.mod contains a dependency that is not vendored, so we won't risk bad builds.

Another note is, when we have vendor, go mod download is not necessary because go will use the content of the vendor folder.

**Pull request merged**
