### PR TITLE
Bug 2017566: Remove unused addresspool name field

### PR DESCRIPTION
**Pull request by msherif1234**
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

**Comment by msherif1234** [comment]
u/s sync with #37 will bring in this fix d/s

**Comment by fedepaol** [comment]
@msherif1234 CI failed, I think this requires the refactoring too.
Maybe it's worth doing a full sync?

**Comment by fedepaol** [comment]
> @msherif1234 CI failed, I think this requires the refactoring too. Maybe it's worth doing a full sync?

Never mind, I just saw your comment above.

**Comment by msherif1234** [comment]
fix is merged under https://github.com/openshift/metallb-operator/pull/37

**Pull request closed without merging**
